# Generated by Django 2.1.5 on 2019-02-21 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good_type',
            name='ctime',
        ),
    ]
