# Generated by Django 2.1.5 on 2019-02-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20190221_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='xiala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('img', models.ImageField(upload_to='', verbose_name='图片')),
                ('note', models.CharField(blank=True, max_length=20, null=True, verbose_name='说明')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '下拉页',
                'verbose_name': '下拉页',
            },
        ),
        migrations.DeleteModel(
            name='Shop_car',
        ),
    ]
