# Generated by Django 2.1.5 on 2019-02-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20190221_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='cart',
            name='goods',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='cart',
            name='is_del',
            field=models.SmallIntegerField(choices=[(0, '不删除'), (1, '删除')], default=0, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '不启用'), (1, '启用')], default=1, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='xiala',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='名称'),
        ),
    ]
