# Generated by Django 2.1.5 on 2019-02-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20190221_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xiala',
            name='img',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='图片'),
        ),
    ]
