# Generated by Django 2.1.5 on 2019-02-21 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20190221_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='good_type',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
        migrations.AddField(
            model_name='good_type',
            name='goods',
            field=models.ManyToManyField(through='app1.Cart', to=settings.AUTH_USER_MODEL, verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete='商品ID', to='app1.Good_type'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete='用户ID', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
    ]
