# Generated by Django 2.1.5 on 2019-02-27 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20190221_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods_recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('status', models.SmallIntegerField(choices=[(0, '启用'), (1, '不启用')], default=0, verbose_name='是否启用')),
                ('note', models.CharField(blank=True, max_length=30, null=True, verbose_name='说明')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('img', models.ImageField(upload_to='picture/', verbose_name='图片')),
                ('good_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Good_type', verbose_name='商品分类id')),
            ],
        ),
    ]
