# Generated by Django 2.1.5 on 2019-02-28 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_goods_recommend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('goods_name', models.CharField(max_length=20, verbose_name='商品名称')),
                ('price', models.FloatField(verbose_name='商品价格')),
                ('count', models.IntegerField(verbose_name='商品数量')),
                ('img', models.ImageField(upload_to='', verbose_name='商品图片')),
                ('total', models.IntegerField(verbose_name='商品总价')),
                ('is_pay', models.SmallIntegerField(choices=[(0, '未支付'), (1, '已支付')], default=0, verbose_name='是否支付')),
            ],
            options={
                'verbose_name_plural': '订单商品表',
                'verbose_name': '订单商品表',
            },
        ),
        migrations.CreateModel(
            name='Order_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=20, null=True, verbose_name='用户id')),
                ('order_no', models.CharField(max_length=100, null=True, verbose_name='订单编号')),
                ('is_pay', models.SmallIntegerField(choices=[(0, '未支付'), (1, '已支付')], default=0, verbose_name='支付状态')),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('allmoney', models.CharField(max_length=20, null=True, verbose_name='总价')),
            ],
            options={
                'verbose_name_plural': '订单列表',
                'verbose_name': '订单列表',
            },
        ),
        migrations.RemoveField(
            model_name='goods_recommend',
            name='good_type',
        ),
        migrations.DeleteModel(
            name='Goods_recommend',
        ),
        migrations.AddField(
            model_name='order_goods',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Order_list', verbose_name='订单列表'),
        ),
    ]
